[package]
name = "crop_domain"
version = "0.1.0"
authors = ["AtsukiTak <takatomgoo@gmail.com>"]
edition = "2018"

[dependencies]
chrono = { version = "~0.4", features = ["serde"] }
derive_more = "~0.99"
rand = "~0.7"
serde = { version = "~1.0", features = ["derive", "rc"] }
uuid = { version = "~0.8", features = ["v4", "serde"] }
