# Production context: All deploys to the main
# repository branch will inherit these settings.
[context.production]
  command = "yarn build"

# Branch deploy context: All deploys that are not in
# an active Deploy Preview will inherit these settings.
[context.branch-deploy]
  command = "yarn build"
