steps:
- name: 'gcr.io/cloud-builders/docker'
  args: [ 'build', '-t', 'gcr.io/$PROJECT_ID/backend', '.' ]
  timeout: '300s'
- name: 'gcr.io/cloud-builders/gcloud'
  args: [ 'app', 'deploy' ]
  timeout: '300s'
images:
- 'gcr.io/$PROJECT_ID/backend'
