steps:
- name: 'gcr.io/kaniko-project/executor:latest'
  args: 
  - --build-arg=BUILD_MODE=$BRANCH_NAME
  - --dockerfile=appengine/Dockerfile
  - --destination=gcr.io/$PROJECT_ID/eagna-api-server:$BRANCH_NAME
  - --cache=true
  dir: 'backend'
- name: 'gcr.io/cloud-builders/gcloud'
  args:
  - 'app'
  - 'deploy'
  - 'appengine/app.yaml'
  - '--image-url=gcr.io/$PROJECT_ID/eagna-api-server:$BRANCH_NAME'
  dir: 'backend'
timeout: '1800s'
