steps:
- name: 'gcr.io/cloud-builders/docker'
  args:
  - 'build'
  - '-t'
  - 'gcr.io/$PROJECT_ID/backend:$SHORT_SHA'
  - '-t'
  - 'gcr.io/$PROJECT_ID/backend:$BRANCH_NAME'
  - '-t'
  - 'gcr.io/$PROJECT_ID/backend:latest'
  - '.'
  dir: 'backend'
images:
- 'gcr.io/$PROJECT_ID/backend:$SHORT_SHA'
- 'gcr.io/$PROJECT_ID/backend:$BRANCH_NAME'
- 'gcr.io/$PROJECT_ID/backend:$latest'
