steps:
- name: 'gcr.io/kaniko-project/executor:latest'
  args: 
  - --build-arg=BUILD_MODE=$_BUILD_MODE
  - --dockerfile=appengine/Dockerfile
  - --context=dir:///workspace/backend
  - --destination=gcr.io/$PROJECT_ID/eagna-api-server:$_BUILD_MODE
  - --cache=true
  dir: 'backend'
- name: 'gcr.io/cloud-builders/gcloud'
  args:
  - 'app'
  - 'deploy'
  - 'appengine/app.yaml'
  - '--image-url=gcr.io/$PROJECT_ID/eagna-api-server:$_BUILD_MODE'
  dir: 'backend'
timeout: '1800s'
