version: '3'
services:
  backend:
    build:
      context: .
      args:
        BUILD_MODE: debug
    environment:
      RUST_LOG: warn,libeagna=debug,eagna=debug
      RUST_BACKTRACE: 1
      DATABASE_URL: postgres://postgres:postgres@pg/postgres
      PORT: 8080
      SECRET: "hogehoge"
    ports:
      - '8080:8080'
  pg:
    image: postgres:10
    ports:
      - '5432:5432'
  postgres-gui:
    image: sosedoff/pgweb
    command: sh -c "sleep 30 && /usr/bin/pgweb --bind=0.0.0.0 --listen=11080 --url postgresql://postgres:@pg/postgres?sslmode=disable"
    depends_on:
      - pg
    ports:
      - "11080:11080"
