version: '3'
services:
  backend:
    image: node
    build:
      context: .
      args:
        BUILD_MODE: debug
    environment:
      RUST_LOG: warn,libeagna=debug,eagna=debug
      PG_URL: postgres://postgres:postgres@pg/postgres
      REDIS_URL: redis://rd:6379
      PORT: 8080
      ACCESS_ALLOW_HOSTS: '*'
    ports:
      - '8080:8080'
  pg:
    image: postgres:10
    ports:
      - '5432:5432'
  redis:
    image: redis
    ports:
      - '6379:6379'
    command: redis-server --bind 0.0.0.0
  postgres-gui:
    image: sosedoff/pgweb
    command: sh -c "sleep 30 && /usr/bin/pgweb --bind=0.0.0.0 --listen=11080 --url postgresql://postgres:@pg/postgres?sslmode=disable"
    depends_on:
      - pg
    ports:
      - "11080:11080"
