runtime: custom
env: flex
env_variables:
  BIND: 0.0.0.0:8080
  RUST_LOG: warn,libeagna=info,eagna=info
  ACCESS_ALLOW_HOSTS: "*"
resources:
  cpu: 1
  memory_gb: 0.5
  disk_size_gb: 10
automatic_scaling:
  max_num_instances: 1
