[package]
name = "utils"
version = "0.1.0"
authors = ["AtsukiTak <takatomgoo@gmail.com>"]
edition = "2018"

[dependencies]
diesel = { version = "~1.4", features = ["postgres"] }
chrono = { version = "~0.4", features = ["serde"] }
rohanmarket-backend = { path = ".." }
