[package]
name = "utils"
version = "0.1.0"
authors = ["AtsukiTak <takatomgoo@gmail.com>"]
edition = "2018"

[dependencies]
chrono = { version = "~0.4" }
rohanmarket-backend = { path = ".." }

[[bin]]
name = "feed_demo_data"
path = "src/bin/feed_demo_data.rs"
