[package]
name = "crop"
version = "0.1.0"
authors = ["AtsukiTak <takatomgoo@gmail.com>"]
edition = "2018"

[dependencies]
crop_app = { path = "../crop_app" }

env_logger = "0.7"
log = "~0.4"
tokio = { version = "0.2", features = ["macros", "rt-threaded"] }
