name: Rust

on:
  push:
    branches:
      - master
    paths:
      - '.github/workflows/rust.yml'
      - 'backend/**'
  pull_request:
    branches:
      - master
    paths:
      - '.github/workflows/rust.yml'
      - 'backend/**'

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Cache cargo registry
      uses: actions/cache@v1
      with:
        path: ~/.cargo/registry
        key: ${{ runner.os }}-cargo-build-target-${{ hashFiles('backend/Cargo.lock') }}
    - name: Cache cargo index
      uses: actions/cache@v1
      with:
        path: ~/.cargo/git
        key: ${{ runner.os }}-cargo-build-target-${{ hashFiles('backend/Cargo.lock') }}
    - name: Cache cargo check
      uses: actions/cache@v1
      with:
        path: backend/target
        key: ${{ runner.os }}-cargo-build-target-${{ hashFiles('backend/Cargo.lock') }}
    - name: Check
      run: cd backend && cargo check
    - name: Check lint
      run: cd backend && cargo-clippy
    - name: Check format
      run: cd backend && cargo fmt -- --check
