name: Rust

on:
  push:
    branches:
      - master
    paths:
      - 'backend/Cargo.toml'
      - 'backend/Cargo.lock'
      - 'backend/src/**.rs'
  pull_request:
    branches:
      - master
    paths:
      - 'backend/Cargo.toml'
      - 'backend/Cargo.lock'
      - 'backend/src/**.rs'

jobs:
  test:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Check
      run: cd backend && cargo check
    - name: Build
      run: cd backend && cargo build --verbose
    - name: Cache cargo build
      uses: actions/cache@v1
      with:
        path: backend/target
        key: ${{ runner.os }}-cargo-build-target-${{ hashFiles('backend/Cargo.lock') }}
    - name: Run tests
      run: cd backend && cargo test --verbose
